# Site settings
title: Ghanan
name: Ghanan
email: me@ghanan.ca
description: > # this means to ignore newlines until "baseurl:"
  My personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ghanan.ca" # the base hostname & protocol for your site
social:
  github: http://github.com/ghanan94
  twitter:
  facebook:
  pinterest:
  linkedin: http://ca.linkedin.com/in/ghanan94

# Build settings
markdown: kramdown

#Sass Settings
sass:
  sass_dir: assets/stylesheets
