# Site settings
title: Ghanan
email: me@ghanan.ca
description: > # this means to ignore newlines until "baseurl:"
  My personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ghanan.ca" # the base hostname & protocol for your site
twitter_username: 
github_username:  ghanan94

# Build settings
markdown: kramdown

#Sass Settings
sass:
  sass_dir: assets/stylesheets
